export const compConst = {
    LOAD_COMPETITION: "LOAD_COMPETITION",

    CREATE_COMPETITION_REQUEST: "CREATE_COMPETITION_REQUEST",
    CREATE_COMPETITION_SUCCESS: "CREATE_COMPETITION_SUCCESS",
    CREATE_COMPETITION_FAILURE: "CREATE_COMPETITION_FAILURE"
};
