export const compConst = {
    LOAD_COMPETITION_REQUEST: "LOAD_COMPETITION_REQUEST",
    LOAD_COMPETITION_SUCCESS: "LOAD_COMPETITION_SUCCESS",
    LOAD_COMPETITION_FAILURE: "LOAD_COMPETITION_FAILURE",

    CREATE_COMPETITION_REQUEST: "CREATE_COMPETITION_REQUEST",
    CREATE_COMPETITION_SUCCESS: "CREATE_COMPETITION_SUCCESS",
    CREATE_COMPETITION_FAILURE: "CREATE_COMPETITION_FAILURE"
};
