export const jobsConstants = {
    GET_FILTERED_JOBS_REQUEST: "GET_FILTERED_JOBS_REQUEST",
    GET_FILTERED_JOBS_SUCCESS: "GET_FILTERED_JOBS_SUCCESS",
    GET_FILTERED_JOBS_FAILURE: "GET_FILTERED_JOBS_FAILURE",

    GET_JOB_REQUEST: "GET_JOB_REQUEST",
    GET_JOB_SUCCESS: "GET_JOB_SUCCESS",
    GET_JOB_FAILURE: "GET_JOB_FAILURE"
};
