export const jobsConstants = {
    GET_INTERESTED_JOBS_REQUEST: "GET_INTERESTED_JOBS_REQUEST",
    GET_INTERESTED_JOBS_SUCCESS: "GET_INTERESTED_JOBS_SUCCESS",

    GET_JOB_REQUEST: "GET_JOB_REQUEST",
    GET_JOB_SUCCESS: "GET_JOB_SUCCESS"
};
