export const jobsConstants = {
    GET_FILTERED_JOBS_REQUEST: "GET_FILTERED_JOBS_REQUEST",
    GET_FILTERED_JOBS_SUCCESS: "GET_FILTERED_JOBS_SUCCESS",
    GET_FILTERED_JOBS_FAILURE: "GET_FILTERED_JOBS_FAILURE",

    GET_JOB_REQUEST: "GET_JOB_REQUEST",
    GET_JOB_SUCCESS: "GET_JOB_SUCCESS",
    GET_JOB_FAILURE: "GET_JOB_FAILURE",

    POST_JOB_OFFER_REQUEST: "POST_JOB_OFFER_REQUEST",
    POST_JOB_OFFER_SUCCESS: "POST_JOB_OFFER_SUCCESS",
    POST_JOB_OFFER_FAILURE: "POST_JOB_OFFER_FAILURE",

    APPLY_JOB_REQUEST: "APPLY_JOB_REQUEST",
    APPLY_JOB_SUCCESS: "APPLY_JOB_SUCCESS",
    APPLY_JOB_FAILURE: "APPLY_JOB_FAILURE"
};
