export const messagingConst = {
    GET_LAST_MESSAGES: "GET_LAST_MESSAGES",
    GET_CURRENT_CONVERSATION: "GET_CURRENT_CONVERSATION",

    STORE_LAST_MESSAGES: "STORE_LAST_MESSAGES",
    STORE_CURRENT_CONVERSATION: "STORE_CURRENT_CONVERSATION",

    POST_MESSAGE: "POST_MESSAGE",
    CREATE_NEW_CONVERSATION: "CREATE_NEW_CONVERSATION"
};
