export const orgConst = {
    GET_ALL_REQUEST: "GET_ALL_REQUEST",
    GET_ALL_SUCCESS: "GET_ALL_SUCCESS",

    GET_ORGANISATION_REQUEST: "GET_ORGANISATION_REQUEST",
    GET_ORGANISATION_SUCCESS: "GET_ORGANISATION_SUCCESS",
    GET_ORGANISATION_FAILURE: "GET_ORGANISATION_FAILURE",

    CREATE_NEW_SUCCESS: "CREATE_NEW_SUCCESS",
    CREATE_NEW_REQUEST: "CREATE_NEW_REQUEST",

    EDIT_ORGANISATION_REQUEST: "EDIT_ORGANISATION",
    EDIT_ORGANISATION_SUCCESS: "EDIT_ORGANISATION_SUCCESS",
    EDIT_ORGANISATION_FAILURE: "EDIT_ORGANISATION_FAILURE",

    REQUEST_USERS: "REQUEST_USERS",

    ADD_USER: "ADD_USER"
};
