export const orgConst = {
    GET_ALL_REQUEST: "GET_ALL_REQUEST",
    GET_ALL_SUCCESS: "GET_ALL_SUCCESS",

    CREATE_NEW_SUCCESS: "CREATE_NEW_SUCCESS",
    CREATE_NEW_REQUEST: "CREATE_NEW_REQUEST",

    REQUEST_USERS: "REQUEST_USERS",

    ADD_USER: "ADD_USER"
};
