export const postsConstants = {
    CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

    GET_USER_POSTS_REQUEST: "GET_USER_POSTS_REQUEST",
    GET_USER_POSTS_SUCCESS: "GET_USER_POSTS_SUCCESS",
    GET_USER_POSTS_FAILURE: "GET_USER_POSTS_FAILURE",

    GET_HOME_FEED_REQUEST: "GET_HOME_FEED_REQUEST",
    GET_HOME_FEED_SUCCESS: "GET_HOME_FEED_SUCCESS",
    GET_HOME_FEED_FAILURE: "GET_HOME_FEED_FAILURE",

    LIKE_POST_REQUEST: "LIKE_POST_REQUEST",
    LIKE_POST_SUCCESS: "LIKE_POST_SUCCESS",
    LIKE_POST_FAILURE: "LIKE_POST_FAILURE"
};
