export const postsConstants = {
    CREATE_POST_REQUEST: "CREATE_POST_REQUEST",
    CREATE_POST_SUCCESS: "CREATE_POST_SUCCESS",
    CREATE_POST_FAILURE: "CREATE_POST_FAILURE",

    GET_USER_POSTS_REQUEST: "GET_USER_POSTS_REQUEST",
    GET_USER_POSTS_SUCCESS: "GET_USER_POSTS_SUCCESS",
    GET_USER_POSTS_FAILURE: "GET_USER_POSTS_FAILURE"
};
