export const searchConst = {
    GET_USER_REQUEST: "SEARCH_USER_REQUEST",
    GET_USER_SUCCESS: "SEARCH_USER_SUCCESS",
    GET_USER_FAILURE: "SEARCH_USER_FAILURE",

    GET_ORGANISATION_REQUEST: "SEARCH_ORGANISATION_REQUEST",
    GET_ORGANISATION_SUCCESS: "SEARCH_ORGANISATION_SUCCESS",
    GET_ORGANISATION_FAILURE: "SEARCH_ORGANISATION_FAILURE",

    GET_COMPETITIONS_REQUEST: "SEARCH_COMPETITIONS_REQUEST",
    GET_COMPETITIONS_SUCCESS: "SEARCH_COMPETITIONS_SUCCESS",
    GET_COMPETITIONS_FAILURE: "SEARCH_COMPETITIONS_FAILURE"
};
