export const searchConst = {
    GET_USER_REQUEST: "GET_USER_REQUEST",
    GET_USER_SUCCESS: "GET_USER_SUCCESS",
    GET_USER_FAILURE: "GET_USER_FAILURE",

    GET_ORGANISATION_REQUEST: "GET_ORGANISATION_REQUEST",
    GET_ORGANISATION_SUCCESS: "GET_ORGANISATION_SUCCESS",
    GET_ORGANISATION_FAILURE: "GET_ORGANISATION_FAILURE",

    GET_COMPETITIONS_REQUEST: "GET_COMPETITIONS_REQUEST",
    GET_COMPETITIONS_SUCCESS: "GET_COMPETITIONS_SUCCESS",
    GET_COMPETITIONS_FAILURE: "GET_COMPETITIONS_FAILURE"
};
