export const subscriptionsConstants = {
    GET_PLANS_REQUEST: "GET_PLANS_REQUEST",
    GET_PLANS_SUCCESS: "GET_PLANS_SUCCESS",
    GET_PLANS_FAILURE: "GET_PLANS_FAILURE",

    GET_CATEGORIES_REQUEST: "GET_CATEGORIES_REQUEST",
    GET_CATEGORIES_SUCCESS: "GET_CATEGORIES_SUCCESS",
    GET_CATEGORIES_FAILURE: "GET_CATEGORIES_FAILURE",

    GET_POSTSINCATEGORY_REQUEST: "GET_POSTSINCATEGORY_REQUEST",
    GET_POSTSINCATEGORY_SUCCESS: "GET_POSTSINCATEGORY_SUCCESS",
    GET_POSTSINCATEGORY_FAILURE: "GET_POSTSINCATEGORY_FAILURE",

    POST_ADDUSERTOPLAN_REQUEST: "POST_ADDUSERTOPLAN_REQUEST",
    POST_ADDUSERTOPLAN_SUCCESS: "POST_ADDUSERTOPLAN_SUCCESS",
    POST_ADDUSERTOPLAN_FAILURE: "POST_ADDUSERTOPLAN_FAILURE",

    POST_POSTTOPLAN_REQUEST: "POST_POSTTOPLAN_REQUEST",
    POST_POSTTOPLAN_SUCCESS: "POST_POSTTOPLAN_SUCCESS",
    POST_POSTTOPLAN_FAILURE: "POST_POSTTOPLAN_FAILURE"
};
